language: python
python:
  -  "2.7"
service:
  -  docker
install:
  -  make deps
script:
  -  make lint
  -  make test
  -  make docker_build
  -  make docker_push
deploy:
  -  provider:heroku
  -  app: desolate-tor-28258
  -  api_key:${HEROKU_API_KEY}
